name: talents
description: "A new Flutter project."
 
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  sizer: ^2.0.15
  page_transition: ^2.1.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.6
  video_player: ^2.9.1
  easy_url_launcher: ^0.0.7
  image_picker: ^1.1.2
  animate_do: ^3.3.4
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  conditional_builder_null_safety: ^0.0.6
  file_picker: ^8.0.6
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0
  loading_animation_widget: ^1.2.1
  flutter_widget_from_html_core: ^0.15.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  flutter_local_notifications: ^17.2.4
  chewie: ^1.8.5
  youtube_explode_dart: ^2.3.5
  just_audio: ^0.9.42
   


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



 
flutter:


  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Svg_Icons/

  fonts:
    - family: tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
          weight: 700

    - family: inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
